-- SEED DATA FOR BILLS
-- Run this script in Supabase SQL Editor to populate the sim_bills table

INSERT INTO public.sim_bills (id, week, ppl_number, title, description, category) VALUES
('ppl-2110', 1, 'PPL n°2110', 'Supprimer la prescription pour les viols sur mineurs', 'Rendre imprescriptibles les crimes sexuels commis sur des mineurs.', 'Justice'),
('ppl-2109', 2, 'PPL n°2109', 'Renforcer les peines pour sévices sur animaux', 'Peines jusqu''à 5 ans de prison pour maltraitance animale.', 'Société'),
('ppl-cameras', 3, 'PPL Sécurité', 'Reconnaissance faciale dans l''espace public', 'Autoriser l''usage de la reconnaissance faciale pour la lutte antiterroriste.', 'Sécurité'),
('ppl-cyber', 4, 'PPL Numérique', 'Loi anti-anonymat sur internet', 'Obligation de fournir une identité vérifiée pour créer un compte sur les réseaux sociaux.', 'Numérique'),
('ppl-bitcoin', 5, 'Proposition Ciotti', 'Bitcoin comme réserve de trésorerie publique', 'Autoriser les collectivités à détenir du Bitcoin.', 'Économie'),
('ppl-smic', 6, 'PPL Sociale', 'Revalorisation du SMIC à 1600€ net', 'Augmentation immédiate du salaire minimum.', 'Économie'),
('ppl-superprofits', 7, 'PPL Fiscal', 'Taxe exceptionnelle sur les superprofits', 'Taxation à 50% des bénéfices exceptionnels des grandes entreprises.', 'Finance'),
('ppl-2029', 8, 'PPL n°2029', 'Garantir l''accès à l''argent liquide', 'Obligation d''accepter les espèces partout.', 'Économie'),
('ppl-glyphosate', 9, 'PPL Écologie', 'Interdiction totale du glyphosate', 'Interdiction immédiate sans dérogation.', 'Écologie'),
('ppl-chasse', 10, 'PPL Nature', 'Interdiction de la chasse le dimanche', 'Réserver le dimanche aux promeneurs.', 'Écologie'),
('ppl-megabassines', 11, 'PPL Eau', 'Moratoire sur les méga-bassines', 'Suspension de tous les projets de retenues d''eau agricoles.', 'Agriculture'),
('ppl-bio', 12, 'PPL Cantines', '100% Bio dans les cantines scolaires', 'Obligation de servir uniquement des produits bio à l''école.', 'Éducation'),
('ppl-2065', 13, 'PPL n°2065', 'Gratuité des soins dentaires', 'Prise en charge à 100% par la Sécurité Sociale.', 'Santé'),
('ppl-euthanasie', 14, 'PPL Fin de Vie', 'Légalisation de l''aide active à mourir', 'Droit à l''euthanasie pour les maladies incurables.', 'Santé'),
('ppl-cannabis', 15, 'PPL Santé', 'Légalisation du cannabis récréatif', 'Vente encadrée par l''État dans des officines dédiées.', 'Santé'),
('ppl-deserts', 16, 'PPL Médecins', 'Régulation de l''installation des médecins', 'Interdiction de s''installer en zone sur-dotée.', 'Santé'),
('ppl-4-jours', 17, 'PPL Travail', 'Semaine de 4 jours (32h)', 'Réduction du temps de travail sans perte de salaire.', 'Social'),
('ppl-retraites', 18, 'PPL Retraites', 'Retraite à 60 ans', 'Abrogation de la réforme et retour aux 60 ans.', 'Social'),
('ppl-rsa', 19, 'PPL Solidarité', 'RSA dès 18 ans', 'Extension du RSA aux jeunes de 18-25 ans.', 'Solidarité'),
('ppl-teletravail', 20, 'PPL Travail', 'Droit opposable au télétravail', 'Obligation pour l''employeur d''accepter le télétravail si le poste le permet.', 'Travail'),
('ppl-2111', 21, 'PPL n°2111', 'Apprentissage obligatoire de la natation', 'Garantir le savoir-nager pour tous les enfants.', 'Éducation'),
('ppl-uniforme', 22, 'PPL École', 'Uniforme obligatoire à l''école', 'Port d''une tenue unique dans tous les établissements publics.', 'Éducation'),
('ppl-erasmus', 23, 'PPL Jeunesse', 'Service Civique Européen obligatoire', '6 mois de service civique dans un autre pays de l''UE pour tous les jeunes.', 'Europe'),
('ppl-parcoursup', 24, 'PPL Supérieur', 'Suppression de Parcoursup', 'Retour à une affectation basée sur le baccalauréat et le secteur géographique.', 'Éducation'),
('ppl-2124', 25, 'PPL n°2124', 'Vote des étrangers aux locales', 'Droit de vote aux municipales pour les résidents étrangers.', 'Citoyenneté'),
('ppl-proportionnelle', 26, 'PPL Institutions', 'Proportionnelle intégrale aux législatives', 'Élection des députés au scrutin proportionnel.', 'Institutions'),
('ppl-ric', 27, 'PPL Démocratie', 'Référendum d''Initiative Citoyenne (RIC)', 'Permettre aux citoyens de proposer et voter des lois par référendum.', 'Démocratie'),
('ppl-vote-16ans', 28, 'PPL Jeunesse', 'Droit de vote à 16 ans', 'Abaisser la majorité électorale à 16 ans.', 'Citoyenneté'),
('ppl-train', 29, 'PPL Transports', 'Gratuité des trains régionaux (TER)', 'Rendre les transports régionaux gratuits pour tous.', 'Transports'),
('ppl-jets', 30, 'PPL Climat', 'Interdiction des jets privés', 'Bannir l''usage des jets privés sur le territoire.', 'Écologie'),
('ppl-autoroutes', 31, 'PPL Transports', 'Renationalisation des autoroutes', 'Fin des concessions et retour à la gestion publique.', 'Économie'),
('ppl-zfe', 32, 'PPL Climat', 'Suppression des ZFE', 'Arrêt du déploiement des Zones à Faibles Émissions.', 'Transports'),
('ppl-pub', 33, 'PPL Médias', 'Interdiction de la pub pour les produits polluants', 'Bannir la publicité pour les SUV, l''aérien et la fast-fashion.', 'Écologie'),
('ppl-concentration', 34, 'PPL Médias', 'Loi anti-concentration des médias', 'Limiter drastiquement la possession de médias par des groupes industriels.', 'Culture'),
('ppl-pass-culture', 35, 'PPL Culture', 'Extension du Pass Culture', 'Doubler le montant du Pass Culture pour les 18 ans.', 'Culture'),
('ppl-patrimoine', 36, 'PPL Patrimoine', 'Taxe sur les résidences secondaires', 'Surtaxe pour financer la rénovation du patrimoine.', 'Logement'),
('ppl-proprio', 37, 'PPL Logement', 'Encadrement national des loyers', 'Plafonnement strict des loyers sur tout le territoire.', 'Logement'),
('ppl-2021', 38, 'PPL n°2021', 'Zéro sans-abri', 'Réquisition des logements vacants pour les sans-abri.', 'Solidarité'),
('ppl-airbnb', 39, 'PPL Tourisme', 'Limitation drastique d''Airbnb', 'Limiter la location touristique à 30 jours par an maximum.', 'Logement'),
('ppl-renov', 40, 'PPL Climat', 'Obligation de rénovation thermique', 'Interdiction de vendre ou louer des passoires thermiques (G, F, E).', 'Logement'),
('ppl-frexit', 41, 'PPL Europe', 'Référendum sur le Frexit', 'Consulter les Français sur la sortie de l''UE.', 'Europe'),
('ppl-otan', 42, 'PPL Défense', 'Sortie du commandement intégré de l''OTAN', 'Retrouver une indépendance militaire totale.', 'Défense'),
('ppl-service', 43, 'PPL Armée', 'Rétablissement du Service Militaire', 'Service militaire obligatoire de 10 mois pour tous.', 'Défense'),
('ppl-dev', 44, 'PPL International', 'Aide au développement à 1% du PIB', 'Augmenter massivement l''aide aux pays en développement.', 'International'),
('ppl-voile', 45, 'PPL Laïcité', 'Interdiction du voile dans l''espace public', 'Extension de la loi de 2004 à la rue et aux commerces.', 'Société'),
('ppl-corrida', 46, 'PPL Animaux', 'Abolition de la corrida', 'Interdiction des spectacles taurins avec mise à mort.', 'Culture'),
('ppl-2018', 47, 'PPL n°2018', 'Sécurité sociale funéraire', 'Prise en charge des obsèques par la collectivité.', 'Solidarité'),
('ppl-fetes', 48, 'PPL Laïcité', 'Suppression des jours fériés religieux', 'Remplacement par des jours fériés laïques au choix.', 'Société'),
('ppl-final-1', 49, 'PPL Constitution', 'VIème République', 'Convocation d''une assemblée constituante.', 'Institutions'),
('ppl-final-2', 50, 'PPL Écologie', 'Reconnaissance du crime d''écocide', 'Sanctionner pénalement les atteintes graves à l''environnement.', 'Justice'),
('ppl-final-3', 51, 'PPL Santé', 'Nationalisation de l''industrie pharmaceutique', 'Création d''un pôle public du médicament.', 'Santé'),
('ppl-final-4', 52, 'PPL Budget', 'Budget de l''État 2026', 'Adoption du budget général de la nation.', 'Finance')
ON CONFLICT (id) DO UPDATE SET 
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    week = EXCLUDED.week,
    ppl_number = EXCLUDED.ppl_number;